### PR TITLE
fix: if key/value store already exists use that

### LINKED ISSUE #2278: new event bus breaks sensors
When we update the jetstream eventbus version to 2.9.1, our sensors crashloop with the error below. The only way for us to recover is delete the argo-event namespace and argocd will restore it back to normal.

```
{"level":"info","ts":1666883882.918018,"logger":"argo-events.sensor","caller":"leaderelection/leaderelection.go:144","msg":"Not the LEADER, stand by ...","sensorName":"gcf"}
{"level":"info","ts":1666883889.7350574,"logger":"argo-events.sensor","caller":"leaderelection/leaderelection.go:153","msg":"Becoming a Candidate, stand by ...","sensorName":"gcf"}
{"level":"info","ts":1666884061.5108724,"logger":"argo-events.sensor","caller":"leaderelection/leaderelection.go:150","msg":"I'm the LEADER, starting ...","sensorName":"gcf"}
{"level":"info","ts":1666884061.5112243,"logger":"argo-events.sensor","caller":"base/jetstream.go:80","msg":"NATS auth strategy: Basic","sensorName":"gcf"}
{"level":"info","ts":1666884061.5205114,"logger":"argo-events.sensor","caller":"base/jetstream.go:102","msg":"Connected to NATS Jetstream server.","sensorName":"gcf"}
{"level":"info","ts":1666884061.5221837,"logger":"argo-events.sensor","caller":"base/jetstream.go:115","msg":"No need to create Stream 'default' as it already exists","sensorName":"gcf"}
{"level":"error","ts":1666884061.5252142,"logger":"argo-events.sensor","caller":"sensor/sensor_jetstream.go:60","msg":"failed to Create Key/Value Store for sensor gcf, err: nats: stream name already in use","sensorName":"gcf","stacktrace":"github.com/argoproj/argo-event
s/eventbus/jetstream/sensor.(*SensorJetstream).Initialize\n\t/home/runner/work/argo-events/argo-events/eventbus/jetstream/sensor/sensor_jetstream.go:60\ngithub.com/argoproj/argo-events/sensors.(*SensorContext).listenEvents.func1\n\t/home/runner/work/argo-events/argo-eve
nts/sensors/listener.go:109\ngithub.com/argoproj/argo-events/common.DoWithRetry.func1\n\t/home/runner/work/argo-events/argo-events/common/retry.go:106\nk8s.io/apimachinery/pkg/util/wait.ConditionFunc.WithContext.func1\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.24
.3/pkg/util/wait/wait.go:220\nk8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtectionWithContext\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.24.3/pkg/util/wait/wait.go:233\nk8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtection\n\t/home/runner
/go/pkg/mod/k8s.io/apimachinery@v0.24.3/pkg/util/wait/wait.go:226\nk8s.io/apimachinery/pkg/util/wait.ExponentialBackoff\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.24.3/pkg/util/wait/wait.go:421\ngithub.com/argoproj/argo-events/common.DoWithRetry\n\t/home/runner/w
ork/argo-events/argo-events/common/retry.go:105\ngithub.com/argoproj/argo-events/sensors.(*SensorContext).listenEvents\n\t/home/runner/work/argo-events/argo-events/sensors/listener.go:108\ngithub.com/argoproj/argo-events/sensors.(*SensorContext).Start.func1\n\t/home/run
ner/work/argo-events/argo-events/sensors/listener.go:66"}
{"level":"info","ts":1666884063.061998,"logger":"argo-events.sensor","caller":"base/jetstream.go:80","msg":"NATS auth strategy: Basic","sensorName":"gcf"}
{"level":"info","ts":1666884063.0722675,"logger":"argo-events.sensor","caller":"base/jetstream.go:102","msg":"Connected to NATS Jetstream server.","sensorName":"gcf"}
{"level":"info","ts":1666884063.0728028,"logger":"argo-events.sensor","caller":"base/jetstream.go:115","msg":"No need to create Stream 'default' as it already exists","sensorName":"gcf"}
{"level":"error","ts":1666884063.0752885,"logger":"argo-events.sensor","caller":"sensor/sensor_jetstream.go:60","msg":"failed to Create Key/Value Store for sensor gcf, err: nats: stream name already in use","sensorName":"gcf","stacktrace":"github.com/argoproj/argo-event
s/eventbus/jetstream/sensor.(*SensorJetstream).Initialize\n\t/home/runner/work/argo-events/argo-events/eventbus/jetstream/sensor/sensor_jetstream.go:60\ngithub.com/argoproj/argo-events/sensors.(*SensorContext).listenEvents.func1\n\t/home/runner/work/argo-events/argo-eve
nts/sensors/listener.go:109\ngithub.com/argoproj/argo-events/common.DoWithRetry.func1\n\t/home/runner/work/argo-events/argo-events/common/retry.go:106\nk8s.io/apimachinery/pkg/util/wait.ConditionFunc.WithContext.func1\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.24
.3/pkg/util/wait/wait.go:220\nk8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtectionWithContext\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.24.3/pkg/util/wait/wait.go:233\nk8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtection\n\t/home/runner
/go/pkg/mod/k8s.io/apimachinery@v0.24.3/pkg/util/wait/wait.go:226\nk8s.io/apimachinery/pkg/util/wait.ExponentialBackoff\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.24.3/pkg/util/wait/wait.go:421\ngithub.com/argoproj/argo-events/common.DoWithRetry\n\t/home/runner/w
ork/argo-events/argo-events/common/retry.go:105\ngithub.com/argoproj/argo-events/sensors.(*SensorContext).listenEvents\n\t/home/runner/work/argo-events/argo-events/sensors/listener.go:108\ngithub.com/argoproj/argo-events/sensors.(*SensorContext).Start.func1\n\t/home/run
ner/work/argo-events/argo-events/sensors/listener.go:66"}
{"level":"info","ts":1666884064.3643985,"logger":"argo-events.sensor","caller":"base/jetstream.go:80","msg":"NATS auth strategy: Basic","sensorName":"gcf"}
{"level":"info","ts":1666884064.370844,"logger":"argo-events.sensor","caller":"base/jetstream.go:102","msg":"Connected to NATS Jetstream server.","sensorName":"gcf"}
{"level":"info","ts":1666884064.37135,"logger":"argo-events.sensor","caller":"base/jetstream.go:115","msg":"No need to create Stream 'default' as it already exists","sensorName":"gcf"}
{"level":"error","ts":1666884064.373799,"logger":"argo-events.sensor","caller":"sensor/sensor_jetstream.go:60","msg":"failed to Create Key/Value Store for sensor gcf, err: nats: stream name already in use","sensorName":"gcf","stacktrace":"github.com/argoproj/argo-events
/eventbus/jetstream/sensor.(*SensorJetstream).Initialize\n\t/home/runner/work/argo-events/argo-events/eventbus/jetstream/sensor/sensor_jetstream.go:60\ngithub.com/argoproj/argo-events/sensors.(*SensorContext).listenEvents.func1\n\t/home/runner/work/argo-events/argo-even
ts/sensors/listener.go:109\ngithub.com/argoproj/argo-events/common.DoWithRetry.func1\n\t/home/runner/work/argo-events/argo-events/common/retry.go:106\nk8s.io/apimachinery/pkg/util/wait.ConditionFunc.WithContext.func1\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.24.
3/pkg/util/wait/wait.go:220\nk8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtectionWithContext\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.24.3/pkg/util/wait/wait.go:233\nk8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtection\n\t/home/runner/
go/pkg/mod/k8s.io/apimachinery@v0.24.3/pkg/util/wait/wait.go:226\nk8s.io/apimachinery/pkg/util/wait.ExponentialBackoff\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.24.3/pkg/util/wait/wait.go:421\ngithub.com/argoproj/argo-events/common.DoWithRetry\n\t/home/runner/wo
rk/argo-events/argo-events/common/retry.go:105\ngithub.com/argoproj/argo-events/sensors.(*SensorContext).listenEvents\n\t/home/runner/work/argo-events/argo-events/sensors/listener.go:108\ngithub.com/argoproj/argo-events/sensors.(*SensorContext).Start.func1\n\t/home/runn
er/work/argo-events/argo-events/sensors/listener.go:66"}
{"level":"info","ts":1666884066.1804144,"logger":"argo-events.sensor","caller":"base/jetstream.go:80","msg":"NATS auth strategy: Basic","sensorName":"gcf"}
{"level":"info","ts":1666884066.1925776,"logger":"argo-events.sensor","caller":"base/jetstream.go:102","msg":"Connected to NATS Jetstream server.","sensorName":"gcf"}
{"level":"info","ts":1666884066.194199,"logger":"argo-events.sensor","caller":"base/jetstream.go:115","msg":"No need to create Stream 'default' as it already exists","sensorName":"gcf"}
{"level":"error","ts":1666884066.1979318,"logger":"argo-events.sensor","caller":"sensor/sensor_jetstream.go:60","msg":"failed to Create Key/Value Store for sensor gcf, err: nats: stream name already in use","sensorName":"gcf","stacktrace":"github.com/argoproj/argo-event
s/eventbus/jetstream/sensor.(*SensorJetstream).Initialize\n\t/home/runner/work/argo-events/argo-events/eventbus/jetstream/sensor/sensor_jetstream.go:60\ngithub.com/argoproj/argo-events/sensors.(*SensorContext).listenEvents.func1\n\t/home/runner/work/argo-events/argo-eve
nts/sensors/listener.go:109\ngithub.com/argoproj/argo-events/common.DoWithRetry.func1\n\t/home/runner/work/argo-events/argo-events/common/retry.go:106\nk8s.io/apimachinery/pkg/util/wait.ConditionFunc.WithContext.func1\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.24
.3/pkg/util/wait/wait.go:220\nk8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtectionWithContext\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.24.3/pkg/util/wait/wait.go:233\nk8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtection\n\t/home/runner
/go/pkg/mod/k8s.io/apimachinery@v0.24.3/pkg/util/wait/wait.go:226\nk8s.io/apimachinery/pkg/util/wait.ExponentialBackoff\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.24.3/pkg/util/wait/wait.go:421\ngithub.com/argoproj/argo-events/common.DoWithRetry\n\t/home/runner/w
ork/argo-events/argo-events/common/retry.go:105\ngithub.com/argoproj/argo-events/sensors.(*SensorContext).listenEvents\n\t/home/runner/work/argo-events/argo-events/sensors/listener.go:108\ngithub.com/argoproj/argo-events/sensors.(*SensorContext).Start.func1\n\t/home/run
ner/work/argo-events/argo-events/sensors/listener.go:66"}
{"level":"info","ts":1666884067.8530138,"logger":"argo-events.sensor","caller":"base/jetstream.go:80","msg":"NATS auth strategy: Basic","sensorName":"gcf"}
{"level":"info","ts":1666884067.860567,"logger":"argo-events.sensor","caller":"base/jetstream.go:102","msg":"Connected to NATS Jetstream server.","sensorName":"gcf"}
{"level":"info","ts":1666884067.8610892,"logger":"argo-events.sensor","caller":"base/jetstream.go:115","msg":"No need to create Stream 'default' as it already exists","sensorName":"gcf"}
{"level":"error","ts":1666884067.8636787,"logger":"argo-events.sensor","caller":"sensor/sensor_jetstream.go:60","msg":"failed to Create Key/Value Store for sensor gcf, err: nats: stream name already in use","sensorName":"gcf","stacktrace":"github.com/argoproj/argo-event
s/eventbus/jetstream/sensor.(*SensorJetstream).Initialize\n\t/home/runner/work/argo-events/argo-events/eventbus/jetstream/sensor/sensor_jetstream.go:60\ngithub.com/argoproj/argo-events/sensors.(*SensorContext).listenEvents.func1\n\t/home/runner/work/argo-events/argo-eve
nts/sensors/listener.go:109\ngithub.com/argoproj/argo-events/common.DoWithRetry.func1\n\t/home/runner/work/argo-events/argo-events/common/retry.go:106\nk8s.io/apimachinery/pkg/util/wait.ConditionFunc.WithContext.func1\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.24
.3/pkg/util/wait/wait.go:220\nk8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtectionWithContext\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.24.3/pkg/util/wait/wait.go:233\nk8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtection\n\t/home/runner
/go/pkg/mod/k8s.io/apimachinery@v0.24.3/pkg/util/wait/wait.go:226\nk8s.io/apimachinery/pkg/util/wait.ExponentialBackoff\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.24.3/pkg/util/wait/wait.go:421\ngithub.com/argoproj/argo-events/common.DoWithRetry\n\t/home/runner/w
ork/argo-events/argo-events/common/retry.go:105\ngithub.com/argoproj/argo-events/sensors.(*SensorContext).listenEvents\n\t/home/runner/work/argo-events/argo-events/sensors/listener.go:108\ngithub.com/argoproj/argo-events/sensors.(*SensorContext).Start.func1\n\t/home/run
ner/work/argo-events/argo-events/sensors/listener.go:66"}
{"level":"fatal","ts":1666884067.8637202,"logger":"argo-events.sensor","caller":"sensors/listener.go:67","msg":"failed to start","sensorName":"gcf","error":"failed after retries: nats: stream name already in use","stacktrace":"github.com/argoproj/argo-events/sensors.(*S
ensorContext).Start.func1\n\t/home/runner/work/argo-events/argo-events/sensors/listener.go:67"}
```

### PR DESCRIPTION
**Pull request by juliev0**
Fixes #2278 

Use the existing key/value store if it already exists.

I tested this with the following experiments involving a webhook and a sensor with a trigger that is configured as "A&&B":
- start up new jetstream bus where key/value store doesn't already exist 
- use existing jetstream bus, send "A", modify jetstream version and `kubectl apply` it, send "B", verify trigger occurs
- use existing jetstream bus, send "A", delete sensor pod and see it restart, send "B", verify trigger occurs

Signed-off-by: Julie Vogelman <julie_vogelman@intuit.com>

### CODE REVIEW

File: eventbus/jetstream/sensor/sensor_jetstream.go [hunk 1]
```diff
@@ -55,12 +55,22 @@ func (stream *SensorJetstream) Initialize() error {
 	}
 	// create Key/Value store for this Sensor (seems to be okay to call this if it already exists)
 	stream.keyValueStore, err = stream.MgmtConnection.JSContext.CreateKeyValue(&nats.KeyValueConfig{Bucket: stream.sensorName})
-	if err != nil {
+	switch err {
```
Comment (whynowy) [inline eventbus/jetstream/sensor/sensor_jetstream.go:58]: Can we query first, if it's not existing, then create it?

Comment (juliev0) [reply eventbus/jetstream/sensor/sensor_jetstream.go]: done

**Review by whynowy — APPROVED** [review]
LGTM
