### PR TITLE
fix: prevent minio bucket notification error swallowing

### LINKED ISSUE #963: Minio bucket notification error getting swallowed
**Describe the bug**
Minio event source implementation swallows errors upon listing to notifications, logging a generic `invalid notification` message instead of the original error.

**To Reproduce**
Provide wrong settings to minio event source.

**Expected behavior**
Error should be specific to facilitate troubleshooting.

**Environment (please complete the following information):**
 - Kubernetes: v1.19.2
 - Argo Events: v1.0.0

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

### PR DESCRIPTION
**Pull request by pierreyves-lebrun**
Checklist:

* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo-events/blob/master/USERS.md).

Fixes #963

### CODE REVIEW

File: eventsources/sources/minio/start.go [hunk 1]
```diff
@@ -86,7 +86,7 @@ func (el *EventListener) StartListening(ctx context.Context, dispatch func([]byt
 	log.Info("started listening to bucket notifications...")
 	for notification := range minioClient.ListenBucketNotification(minioEventSource.Bucket.Name, prefix, suffix, minioEventSource.Events, doneCh) {
 		if notification.Err != nil {
-			log.Errorw("invalid notification", zap.Error(err))
+			log.Errorw("invalid notification", zap.Error(notification.Err))
```
Comment (whynowy) [inline eventsources/sources/minio/start.go:89]: Thanks for fixing it!

File: USERS.md [hunk 2]
```diff
@@ -11,3 +11,4 @@ Organizations below are **officially** using Argo Events. Please send a PR with
 1. [InsideBoard](https://www.insideboard.com)
 1. [Intuit](https://www.intuit.com/)
 1. [Viaduct](https://www.viaduct.ai/)
+1. [Rakuten](https://www.rakuten.com)
```
Comment (whynowy) [inline USERS.md:14]: Could you put it 1 line above (alphabetical order)?

**Review by whynowy — APPROVED** [review]
LGTM!
