### PR TITLE
Fix: Issue 1545: Username/password authentication for AMQP

### LINKED ISSUE #1545: AMQP EventSource connection stuck at "started processing" state
**Describe the bug**

The EventSource is added without any issues, but there is no visible connection to RabbitMQ. When looking at the pod's log I see  that the connection process keeps printing `"started processing the AMQP event source..."` without any error message.

```
{"level":"info","ts":1643026693.572316,"logger":"argo-events.eventsource","caller":"cmd/start.go:63","msg":"starting eventsource server","eventSourceName":"argo-events-rabbitmq-event-source-dev-sandbox","version":"v1.5.6"}
{"level":"info","ts":1643026693.5732281,"logger":"argo-events.eventsource","caller":"metrics/metrics.go:172","msg":"starting metrics server","eventSourceName":"argo-events-rabbitmq-event-source-dev-sandbox"}
{"level":"info","ts":1643026693.5783186,"logger":"argo-events.eventsource","caller":"leaderelection/leaderelection.go:122","msg":"Not the LEADER, stand by ...","eventSourceName":"argo-events-rabbitmq-event-source-dev-sandbox"}
{"level":"info","ts":1643026694.479639,"logger":"argo-events.eventsource","caller":"leaderelection/leaderelection.go:131","msg":"Becoming a Candidate, stand by ...","eventSourceName":"argo-events-rabbitmq-event-source-dev-sandbox"}
{"level":"info","ts":1643026694.4800801,"logger":"argo-events.eventsource","caller":"leaderelection/leaderelection.go:128","msg":"I'm the LEADER, starting ...","eventSourceName":"argo-events-rabbitmq-event-source-dev-sandbox"}
{"level":"info","ts":1643026694.4801247,"logger":"argo-events.eventsource","caller":"eventsources/eventing.go:318","msg":"Starting event source server...","eventSourceName":"argo-events-rabbitmq-event-source-dev-sandbox"}
{"level":"info","ts":1643026694.480536,"logger":"argo-events.eventsource","caller":"driver/nats.go:93","msg":"NATS auth strategy: Token","eventSourceName":"argo-events-rabbitmq-event-source-dev-sandbox","clientID":"client-argo-events-rabbitmq-event-source-dev-sandbox-eventsource-h2v62-675"}
{"level":"info","ts":1643026694.4826007,"logger":"argo-events.eventsource","caller":"driver/nats.go:105","msg":"Connected to NATS server.","eventSourceName":"argo-events-rabbitmq-event-source-dev-sandbox","clientID":"client-argo-events-rabbitmq-event-source-dev-sandbox-eventsource-h2v62-675"}
{"level":"info","ts":1643026694.4841583,"logger":"argo-events.eventsource","caller":"driver/nats.go:118","msg":"Connected to NATS streaming server.","eventSourceName":"argo-events-rabbitmq-event-source-dev-sandbox","clientID":"client-argo-events-rabbitmq-event-source-dev-sandbox-eventsource-h2v62-675"}
{"level":"info","ts":1643026694.4841876,"logger":"argo-events.eventsource","caller":"eventsources/eventing.go:438","msg":"Eventing server started.","eventSourceName":"argo-events-rabbitmq-event-source-dev-sandbox"}
{"level":"info","ts":1643026694.484225,"logger":"argo-events.eventsource","caller":"eventsources/eventing.go:341","msg":"starting eventbus connection daemon...","eventSourceName":"argo-events-rabbitmq-event-source-dev-sandbox"}
{"level":"info","ts":1643026694.4842942,"logger":"argo-events.eventsource","caller":"amqp/start.go:66","msg":"started processing the AMQP event source...","eventSourceName":"argo-events-rabbitmq-event-source-dev-sandbox","eventSourceType":"amqp","eventName":"fileUploadSucceess"}
{"level":"info","ts":1643026715.7225106,"logger":"argo-events.eventsource","caller":"amqp/start.go:66","msg":"started processing the AMQP event source...","eventSourceName":"argo-events-rabbitmq-event-source-dev-sandbox","eventSourceType":"amqp","eventName":"fileUploadSucceess"}
{"level":"info","ts":1643026727.787872,"logger":"argo-events.eventsource","caller":"amqp/start.go:66","msg":"started processing the AMQP event source...","eventSourceName":"argo-events-rabbitmq-event-source-dev-sandbox","eventSourceType":"amqp","eventName":"fileUploadSucceess"}
{"level":"info","ts":1643026742.1286154,"logger":"argo-events.eventsource","caller":"amqp/start.go:66","msg":"started processing the AMQP event source...","eventSourceName":"argo-events-rabbitmq-event-source-dev-sandbox","eventSourceType":"amqp","eventName":"fileUploadSucceess"}
```

(UPDATE: `DEBUG` logs don't show more info either.)

I have a managed Amazon MQ instance and use the `amqps://` protocol, and username and password to connect. I provide no additional TLS configuration.

**Expected behavior**
Connection succeeds or an error is thrown.

**Environment (please complete the following information):**
 - Kubernetes: v1.21 (AWS EKS)
 - Argo: v3.2.6
 - Argo Events: v1.5.6

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

### PR DESCRIPTION
**Pull request by juliev0**
Fixes #1545: Username/password authentication for AMQP

### CODE REVIEW

File: eventsources/sources/amqp/start.go [hunk 1]
```diff
@@ -85,13 +85,13 @@ func (el *EventListener) StartListening(ctx context.Context, dispatch func([]byt
...
-				return errors.Wrap(err, "username not founnd")
+				return errors.Wrap(err, "username not found")
 			}
 			password, err := common.GetSecretFromVolume(amqpEventSource.Auth.Password)
 			if err != nil {
-				return errors.Wrap(err, "password not founnd")
+				return errors.Wrap(err, "password not found")
 			}
-			c.SASL = []amqplib.Authentication{&amqplib.AMQPlainAuth{
+			c.SASL = []amqplib.Authentication{&amqplib.PlainAuth{
```
Comment (juliev0) [inline eventsources/sources/amqp/start.go:94]: Changing to the latter seems to work.

I was able to find descriptions of AMQPLAIN and PLAIN here: https://www.rabbitmq.com/access-control.html
Apparently, AMQPLAIN (which we were using) is the non-standard version of PLAIN.

**Comment by juliev0** [comment]
@whynowy can you review this?

**Review by whynowy — APPROVED** [review]
LGTM, thanks!
