### PR TITLE
fix: Add logic to ticker loop to ensure subscription always exists with an open connection

### LINKED ISSUE #860: If subscribe to event bus fails the sensor ends up in a state without a subscription
**Describe the bug**
If the sensor reconnects to the nats server it needs to recreate the subject subscription. If the connection succeeds but re-subscribe does not, the sensor ends up in a state without an active subscription. This causes the sensor to be in a useless state where it's sitting with an open connection to a nats server but not receiving any messages.

Edit:
This bad state can occur if subscribing fails during startup as well.

**Expected behavior**
The sensor should continue attempting to create the subscription, probably at the cadence of this ticker https://github.com/argoproj/argo-events/blob/master/sensors/listener.go#L167 is fine.

**Screenshots**
Example logs of this event occurring: 

```json
{"level":"info","ts":1599069602.989456,"logger":"argo-events.sensor","caller":"sensors/listener.go:175","msg":"reconnected to NATS streaming server.","sensorName":"*************","clientID":"client-3409727250"}
{"level":"info","ts":1599069602.9895031,"logger":"argo-events.sensor","caller":"driver/nats.go:165","msg":"closing subscription...","sensorName":"*************","clientID":"client-3409727250"}
{"level":"info","ts":1599069602.9895215,"logger":"argo-events.sensor","caller":"driver/nats.go:167","msg":"subscription on subject eventbus-argo-events closed","sensorName":"*************","clientID":"client-3409727250"}
{"level":"info","ts":1599069604.9898312,"logger":"argo-events.sensor","caller":"sensors/listener.go:181","msg":"started to re-subscribe events for triggers [*************] with client client-3409727250","sensorName":"*************"}
{"level":"error","ts":1599069606.9958572,"logger":"argo-events.sensor","caller":"driver/nats.go:153","msg":"failed to subscribe to subject eventbus-argo-events","sensorName":"*************","clientID":"client-3409727250","stacktrace":"github.com/argoproj/argo-events/eventbus/driver.(*natsStreaming).SubscribeEventSources\n\t/home/runner/work/argo-events/argo-events/eventbus/driver/nats.go:153\ngithub.com/argoproj/argo-events/sensors.(*SensorContext).ListenEvents.func1.5\n\t/home/runner/work/argo-events/argo-events/sensors/listener.go:182"}
{"level":"error","ts":1599069607.0044267,"logger":"argo-events.sensor","caller":"sensors/listener.go:184","msg":"failed to re-subscribe to eventbus","sensorName":"*************","clientID":"client-3409727250","error":"stan: subscribe request timeout","stacktrace":"github.com/argoproj/argo-events/sensors.(*SensorContext).ListenEvents.func1.5\n\t/home/runner/work/argo-events/argo-events/sensors/listener.go:184"}
```

**Environment (please complete the following information):**
 - Kubernetes: 1.15
 - Argo: 2.9.5
 - Argo Events: 1.0.0-rc1

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

### PR DESCRIPTION
**Pull request by terev**
## Summary 
Fixes #860

This pr ensures that a subscription exists as long as there's an active connection to the eventbus. 

## Manual test plan
- This was tested locally by installing argo-events and testing my dev sensor image.
- I started an instance of the webhook eventbus/sensor. Then I verified that events flowed to the sensor.
- I then deleted all of the nats eventbus pods to force close the connection `kubectl delete po -n argo-events -l 'eventbus-name=default'`
- Then i verified that the subscription was eventually re-established and events flow correctly
- I repeated the deletion steps to validate that it works multiple times

I couldn't find any tests that touch this area but i could've missed them?

### CODE REVIEW

File: sensors/listener.go [hunk 1]
```diff
@@ -39,6 +40,15 @@ import (
 	sensortriggers "github.com/argoproj/argo-events/sensors/triggers"
 )
 
+func subscribeOnce(subLock *uint32, subscribe func()) {
+	// acquire subLock if not already held
+	if !atomic.CompareAndSwapUint32(subLock, 0, 1) {
```
Comment (whynowy) [inline sensors/listener.go:45]: Learnt something, thanks!

**Review by whynowy — APPROVED** [review]
This looks great! I tested by myself as well by randomly error out the subscription. Thanks for fixing it!
