### PR TITLE
fix: payload serialization in sensor. Fixes #2272

### LINKED ISSUE #2272: Parameterization a block of k8s resource (set of key values)
**Describe the bug**
I am trying to parametrize an entire block of k8s trigger using payload. the payload converted to string with backslashes and can't be injected to overwrite the block. Workflows CRD getting `cannot unmarshall spec: cannot restore struct from: string.`

Here is an example of the sensor:
```apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: example
  namespace: argocd
spec:
  template:
    serviceAccountName: argo-wf
  dependencies:
    - name: example-dep
      eventSourceName: example-event-source
      eventName: event-test
  triggers:
    - template:
        name: example-template
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: injected-block-
              spec:
                entrypoint: main
                arguments:
                  parameters:
                    - name: message
                      value: hello world
                serviceAccountName: argo-wf  
                templates:
                  - name: main
                    container:
                      image: docker/whalesay:latest
                      command: [cowsay]
                      args:
                        - "hello world"
          parameters:
            - src:
                dependencyName: example-dep
                dataKey: body.injected
              dest: spec.templates.0.container```

After debugging the sensor I have found that in line 124 sensors/triggers/params.go get serialized json with backslashes:
```
func ApplyParams(jsonObj []byte, params []v1alpha1.TriggerParameter, events map[string]*v1alpha1.Event) ([]byte, error) {
...
tmp, err := sjson.SetBytes(jsonObj, param.Dest, *value)
...

*values values is:
```
Actual state: "{\"image\":\"docker/whalesay:latest\",\"command\":[\"cowsay\"],\"args\":[\"injected\"]}"
 Desired state: "{"image":"docker/whalesay:latest","command":["cowsay"],"args":["injected"]}"
```

The source of that serialization in github.com/cloudevents/sdk-go/v2 that used in eventbus/stan/sensor.(*STANTriggerConn).Subscribe.func1. 

Better option would be to use this differently and use sjson.SetRawBytes function instead of sjson.SetBytes in sensors/triggers/params.go

**To Reproduce**
1. Deploy the sensor from above.
2. send the following json body to the event source:
```
{
  "injected": {
    "image": "docker/whalesay:latest",
    "command": ,
    "args": [
      "injected"
    ]
  }
}
```
**Expected behavior**
Create a workflow that marshal spec right.

**Screenshots**
Screen Shot 2022-10-25 at 10 37 58

**Environment (please complete the following information):**
 - Kubernetes: v1.24.0
 - ArgoWorkflows: v3.4.2
 - Argo Events: v1.7.3

**Additional context**

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

### PR DESCRIPTION
**Pull request by GoshaDo**
Fixes #2272
Signed-off-by: GoshaDo <goshatoo@gmail.com>

### CODE REVIEW

File: sensors/triggers/params.go [hunk 1]
```diff
@@ -274,10 +293,15 @@ func getValueWithTemplate(value []byte, templString string) (string, error) {
...
 // or an error if it does not exist.
-func getValueByKey(value []byte, key string) (string, error) {
+func getValueByKey(value []byte, key string) (string, string, error) {
 	res := gjson.GetBytes(value, key)
 	if res.Exists() {
-		return res.String(), nil
+		if res.Type.String() == "String" {
+			return res.String(), res.Type.String(), nil
+		} else if res.Type.String() == jsonType {
+			return res.Raw, res.Type.String(), nil
```
Comment (whynowy) [inline sensors/triggers/params.go:302]: What will happen if we always use `Raw`?

File: sensors/triggers/params_test.go [hunk 2]
```diff
@@ -274,7 +274,7 @@ func TestResolveParamValue(t *testing.T) {
 
 	for _, test := range tests {
 		t.Run(test.name, func(t *testing.T) {
-			result, err := ResolveParamValue(test.source, events)
+			result, _, err := ResolveParamValue(test.source, events)
```
[the remark this answers is not in the document]
Comment (GoshaDo) [reply sensors/triggers/params_test.go:277]: I think that GoLand have changed it when I executed the unit tests, and I didn't noticed.
running `git config --local core.fileMode false` on the forked repo. 
maybe its a good idea to tests it, or to write in down in contribution manual.

File: sensors/triggers/params.go (hunk 1 above)
Comment (GoshaDo) [reply sensors/triggers/params.go:302]: It will brake what other function expect to get ( uni-test are failing). I wanted to save the functionality of the function and not barking anything else.

File: USERS.md [hunk 3]
```diff
@@ -40,3 +40,5 @@ Organizations below are **officially** using Argo Events. Please send a PR with
 1. [Yubo](https://www.yubo.live/)
 1. [WooliesX](https://wooliesx.com.au/)
 1. [Woolworths Group](https://www.woolworthsgroup.com.au/)
+1. [Rookout](https://www.rookout.com/)
```
Comment (whynowy) [inline USERS.md:43]: Alphabetical order.

File: sensors/triggers/params.go [hunk 4]
```diff
@@ -161,12 +180,13 @@ func renderEventDataAsJSON(event *v1alpha1.Event) ([]byte, error) {
 
 // helper method to resolve the parameter's value from the src
 // returns an error if the Path is invalid/not found and the default value is nil OR if the eventDependency event doesn't exist and default value is nil
-func ResolveParamValue(src *v1alpha1.TriggerParameterSource, events map[string]*v1alpha1.Event) (*string, error) {
+func ResolveParamValue(src *v1alpha1.TriggerParameterSource, events map[string]*v1alpha1.Event) (*string, string, error) {
```
Comment (whynowy) [inline sensors/triggers/params.go:183]: Can you add more docs about the added returning variable?

File: sensors/triggers/params.go [hunk 5]
```diff
@@ -183,7 +203,7 @@ func ResolveParamValue(src *v1alpha1.TriggerParameterSource, events map[string]*
 			}
 
 			if err == nil {
-				return &resultValue, nil
+				return &resultValue, "", nil
```
Comment (whynowy) [inline sensors/triggers/params.go:206]: Return something instead of `""`?

File: sensors/triggers/params.go [hunk 6]
```diff
@@ -203,52 +223,51 @@ func ResolveParamValue(src *v1alpha1.TriggerParameterSource, events map[string]*
...
 			}
 			fmt.Printf("failed to execute the src event template, falling back to key or value. err: %+v\n", err)
 		}
 		if key != "" {
-			resultValue, err = getValueByKey(eventPayload, key)
+			tmp, typ, err := getValueByKey(eventPayload, key)
+			// For block injection support
+			fmt.Printf("failed to get value by key: %+v\n", err)
```
Comment (whynowy) [inline sensors/triggers/params.go:255]: What is this?

How come we have so many `fmt.Printf` in the code.....

File: sensors/triggers/params.go [hunk 7]
```diff
@@ -203,52 +223,51 @@ func ResolveParamValue(src *v1alpha1.TriggerParameterSource, events map[string]*
...
+		return nil, "", err
 	}
-
 	// Get the value corresponding to specified key or template within event payload
 	if eventPayload != nil {
 		if tmplt != "" {
 			resultValue, err = getValueWithTemplate(eventPayload, tmplt)
 			if err == nil {
-				return &resultValue, nil
+				return &resultValue, "", nil
```
Comment (whynowy) [inline sensors/triggers/params.go:248]: Returning stringType by default?

File: sensors/triggers/params.go (hunk 6 above)
Comment (gosharo) [reply sensors/triggers/params.go:255]: already been there. 
[https://github.com/argoproj/argo-events/blob/25f5a50df5963b0b5c6c7e0508474ade24b715ba/sensors/triggers/params.go#L240](url)
changing it's place  to after the error check

Comment (GoshaDo) [reply sensors/triggers/params.go]: already been there.
[https://github.com/argoproj/argo-events/blob/25f5a50df5963b0b5c6c7e0508474ade24b715ba/sensors/triggers/params.go#L240](https://github.com/argoproj/argo-events/pull/url)
changing it's place to after the error check

File: sensors/triggers/params.go [hunk 8]
```diff
@@ -183,7 +205,7 @@ func ResolveParamValue(src *v1alpha1.TriggerParameterSource, events map[string]*
 			}
 
 			if err == nil {
-				return &resultValue, nil
+				return &resultValue, errorType, nil
```
Comment (whynowy) [inline sensors/triggers/params.go:208]: Is this right? If there's no error, return `errorType`?

The original logic looks very tricky. Can we make it simple like this:

```
if src.Value != nil {
  return *src.Value
} else {
  eventPayload, err = json.Marshal.....
  if err != nil {
    return err
  }
  return string(eventPayload)
}
```

File: sensors/triggers/params.go [hunk 9]
```diff
@@ -203,52 +225,51 @@ func ResolveParamValue(src *v1alpha1.TriggerParameterSource, events map[string]*
...
-				return &resultValue, nil
+				return &resultValue, typ, nil
 			}
 			fmt.Printf("failed to get value by key: %+v\n", err)
 		}
 		// In case neither key nor template resolving was successful, fall back to the default value if exists
 		if src.Value != nil {
 			resultValue = *src.Value
-			return &resultValue, nil
+			return &resultValue, typ, nil
```
Comment (whynowy) [inline sensors/triggers/params.go:266]: Does the `typ` returned here have a value?

File: sensors/triggers/params.go [hunk 10]
```diff
@@ -203,52 +225,51 @@ func ResolveParamValue(src *v1alpha1.TriggerParameterSource, events map[string]*
 	case src.Value != nil:
 		// Use the default value set by the user in case the event is missing
 		resultValue = *src.Value
-		return &resultValue, nil
+		return &resultValue, stringType, nil
 	default:
 		// The parameter doesn't have a default value and is referencing a dependency that is
 		// missing in the received events. This is not an error and may happen with || conditions.
-		return nil, nil
+		return nil, errorType, nil
```
Comment (whynowy) [inline sensors/triggers/params.go:232]: The original return seems to be incorrect, it should return an error.

File: sensors/triggers/params.go (hunk 8 above)
Comment (GoshaDo) [reply sensors/triggers/params.go:208]: have changed the error check just after json.Marshal
about the return, we should return a pointer to the casted eventPayload variable. I think best to write it in memory.

Comment (GoshaDo) [reply sensors/triggers/params.go:208]: and the function returns (*string, string, error)
we can't return error only...

File: sensors/triggers/params.go (hunk 9 above)
Comment (GoshaDo) [reply sensors/triggers/params.go:266]: Right... I will return errorType, because we fail the function

File: sensors/triggers/params.go (hunk 10 above)
Comment (GoshaDo) [reply sensors/triggers/params.go:230]: checkout the comment in lines 230-231

File: sensors/triggers/params.go [hunk 11]
```diff
@@ -179,12 +200,11 @@ func ResolveParamValue(src *v1alpha1.TriggerParameterSource, events map[string]*
 			} else {
 				// Default value doesn't exist so return the whole event payload
 				eventPayload, err = json.Marshal(&event)
+				if err == nil {
```
Comment (whynowy) [inline sensors/triggers/params.go:203]: Why moved here? It changed the behavior. when `src.Value != nil`, it originally returns directly, but now it does not.

File: sensors/triggers/params.go (hunk 10 above)
Comment (whynowy) [reply sensors/triggers/params.go:230]: If that's the case, can you return `stringType` as that's the original expectation?

File: sensors/triggers/params.go [hunk 12]
```diff
@@ -203,52 +223,51 @@ func ResolveParamValue(src *v1alpha1.TriggerParameterSource, events map[string]*
...
+		return nil, errorType, err
 	}
-
 	// Get the value corresponding to specified key or template within event payload
 	if eventPayload != nil {
 		if tmplt != "" {
 			resultValue, err = getValueWithTemplate(eventPayload, tmplt)
 			if err == nil {
-				return &resultValue, nil
+				return &resultValue, errorType, nil
```
Comment (whynowy) [inline sensors/triggers/params.go:248]: Why return `errorType` when `err == nil`?

File: sensors/triggers/params.go [hunk 13]
```diff
@@ -203,52 +223,51 @@ func ResolveParamValue(src *v1alpha1.TriggerParameterSource, events map[string]*
...
-				return &resultValue, nil
+				return &resultValue, typ, nil
 			}
 			fmt.Printf("failed to get value by key: %+v\n", err)
 		}
 		// In case neither key nor template resolving was successful, fall back to the default value if exists
 		if src.Value != nil {
 			resultValue = *src.Value
-			return &resultValue, nil
+			return &resultValue, errorType, nil
```
Comment (whynowy) [inline sensors/triggers/params.go:264]: Why return `errorType`?

File: sensors/triggers/params.go [hunk 14]
```diff
@@ -179,12 +200,11 @@ func ResolveParamValue(src *v1alpha1.TriggerParameterSource, events map[string]*
 			} else {
 				// Default value doesn't exist so return the whole event payload
 				eventPayload, err = json.Marshal(&event)
+				if err == nil {
+					return &resultValue, errorType, nil
```
Comment (whynowy) [inline sensors/triggers/params.go:204]: Why return errorType?

File: sensors/triggers/params.go [hunk 15]
```diff
@@ -160,8 +180,9 @@ func renderEventDataAsJSON(event *v1alpha1.Event) ([]byte, error) {
 }
 
 // helper method to resolve the parameter's value from the src
+// returns value and value type (jsonType or stringType or errorType). jsonType represent a block while stringType represent a single value.
 // returns an error if the Path is invalid/not found and the default value is nil OR if the eventDependency event doesn't exist and default value is nil
-func ResolveParamValue(src *v1alpha1.TriggerParameterSource, events map[string]*v1alpha1.Event) (*string, error) {
+func ResolveParamValue(src *v1alpha1.TriggerParameterSource, events map[string]*v1alpha1.Event) (*string, string, error) {
```
Comment (whynowy) [inline sensors/triggers/params.go:185]: Even you added an `errorType` in the return, but you never checked it. To make it simple, the guideline should be:

1. If there's no error, return `(xxx, xx, nil)`
2. Or return `(nil, "", err)`

File: sensors/triggers/params.go (hunk 9 above)
Comment (whynowy) [reply sensors/triggers/params.go]: It falls back to the default value, does not fail the function.

Comment (GoshaDo) [reply sensors/triggers/params.go]: What do you suggest to return here?

File: sensors/triggers/params.go (hunk 11 above)
Comment (GoshaDo) [reply sensors/triggers/params.go]: reverted

File: sensors/triggers/params.go (hunk 12 above)
Comment (GoshaDo) [reply sensors/triggers/params.go:249]: because the we didn't resolver the param. what are you suggestions ?

File: sensors/triggers/params.go (hunk 10 above)
Comment (GoshaDo) [reply sensors/triggers/params.go:231]: have changed it

File: sensors/triggers/params.go (hunk 15 above)
Comment (GoshaDo) [reply sensors/triggers/params.go:185]: that what originally been there...  reverting those changes..

Comment (GoshaDo) [reply sensors/triggers/params.go:185]: Done

File: sensors/triggers/params.go [hunk 16]
```diff
@@ -203,52 +224,51 @@ func ResolveParamValue(src *v1alpha1.TriggerParameterSource, events map[string]*
...
 		if src.Value != nil {
 			fmt.Printf("failed to parse the event payload, using default value. err: %+v\n", err)
 			resultValue = *src.Value
-			return &resultValue, nil
+			return &resultValue, stringType, nil
 		}
-
 		// Otherwise, return the error
-		return nil, err
+		return nil, errorType, err
```
Comment (whynowy) [inline sensors/triggers/params.go:242]: There's no need to have an `errorType`, since you never checked it.

Simply `return nil, "", err`,

File: sensors/triggers/params.go [hunk 17]
```diff
@@ -203,52 +224,51 @@ func ResolveParamValue(src *v1alpha1.TriggerParameterSource, events map[string]*
...
 	}
-
 	// Get the value corresponding to specified key or template within event payload
 	if eventPayload != nil {
 		if tmplt != "" {
 			resultValue, err = getValueWithTemplate(eventPayload, tmplt)
 			if err == nil {
-				return &resultValue, nil
+				return &resultValue, "", nil
```
Comment (whynowy) [inline sensors/triggers/params.go:249]: What is the reason it returns `""` as the type instead of `stringType` when `err == nil`?

File: sensors/triggers/params.go [hunk 18]
```diff
@@ -203,52 +224,51 @@ func ResolveParamValue(src *v1alpha1.TriggerParameterSource, events map[string]*
...
-				return &resultValue, nil
+				return &resultValue, typ, nil
 			}
 			fmt.Printf("failed to get value by key: %+v\n", err)
 		}
 		// In case neither key nor template resolving was successful, fall back to the default value if exists
 		if src.Value != nil {
 			resultValue = *src.Value
-			return &resultValue, nil
+			return &resultValue, "", nil
```
Comment (whynowy) [inline sensors/triggers/params.go:265]: Why it returns `""` as the type instead of `stringType`?

File: sensors/triggers/params.go [hunk 19]
```diff
@@ -272,12 +292,18 @@ func getValueWithTemplate(value []byte, templString string) (string, error) {
...
-		return res.String(), nil
+		if res.Type.String() == stringType {
+			return res.String(), res.Type.String(), nil
+		} else if res.Type.String() == jsonType {
+			return res.Raw, res.Type.String(), nil
+		}
+		return res.Raw, res.Type.String(), nil
 	}
-	return "", fmt.Errorf("key %s does not exist to in the event payload", key)
+	return "", errorType, fmt.Errorf("key %s does not exist to in the event payload", key)
```
Comment (whynowy) [inline sensors/triggers/params.go:308]: no need to have an `errorType`, same reason as above.

File: sensors/triggers/params.go (hunk 16 above)
Comment (GoshaDo) [reply sensors/triggers/params.go]: removed

File: sensors/triggers/params.go (hunk 17 above)
Comment (GoshaDo) [reply sensors/triggers/params.go]: done

File: sensors/triggers/params.go (hunk 18 above)
Comment (GoshaDo) [reply sensors/triggers/params.go]: done

File: sensors/triggers/params.go (hunk 19 above)
Comment (GoshaDo) [reply sensors/triggers/params.go]: removed

File: sensors/triggers/params.go [hunk 20]
```diff
@@ -272,12 +291,18 @@ func getValueWithTemplate(value []byte, templString string) (string, error) {
...
+func getValueByKey(value []byte, key string) (string, string, error) {
 	res := gjson.GetBytes(value, key)
 	if res.Exists() {
-		return res.String(), nil
+		if res.Type.String() == stringType {
+			return res.String(), res.Type.String(), nil
+		} else if res.Type.String() == jsonType {
+			return res.Raw, res.Type.String(), nil
+		}
+		return res.Raw, res.Type.String(), nil
```
Comment (whynowy) [inline sensors/triggers/params.go:305]: This is the default return, make it consistent as before:

`return res.String(), stringType, nil`

File: sensors/triggers/params.go (hunk 5 above)
Comment (whynowy) [inline sensors/triggers/params.go:206]: `return &resultValue, stringType, nil`

File: sensors/triggers/params.go (hunk 20 above)
Comment (gosharo) [reply sensors/triggers/params.go]: Done
