### PR TITLE
fix: Use different clientID for each EventBus reconnection. Fixes #1055

### LINKED ISSUE #1055: eventsource pods stop functioning after a while
**Describe the bug**
After some time succesfully running multiple eventSources/Sensors, the eventSource listening to minio stops working. It normally listens to s3:ObjectCreated:Put but stops doing that.

Restarting the eventSource POD resolves the issue. But since I don't know when it'll stop working (read: until developers start complaining), this is not a valid workaround.

**To Reproduce**
I really don't know. Last time it happened it was about 30 days ago.

**Expected behavior**
The eventSource should Just Work. 

**Screenshots**
N/A

**Environment (please complete the following information):**
 - Kubernetes: 1.16,8
 - Argo: 2.12.6
 - Argo Events: 1.1.0  (just upgraded to 1.2.2 - haven't seen the long-term use yet)

**Additional context**
The Pods in argo-events ns show many restarts:

```
jumpbox-osr-svm (ota:svmt) ~ $ k get pod -n argo-events
NAME                                                              READY   STATUS    RESTARTS   AGE
eventbus-controller-585f4c97d4-mlfqc                              1/1     Running   0          27d
eventbus-default-stan-0                                           2/2     Running   0          27d
eventbus-default-stan-1                                           2/2     Running   0          27d
eventbus-default-stan-2                                           2/2     Running   0          27d
eventsource-controller-685768bb65-5jk69                           1/1     Running   0          27d
minio-cd-eventsource-n7g67-76f98fcfd9-9vmwg                       1/1     Running   20         27d
minio-cd-sensor-z4kjt-55d97cc66c-x6x2k                            1/1     Running   0          11d
minio-ci-eventsource-cgpv9-54f67d7bb5-nh5j4                       1/1     Running   20         27d
minio-ci-sensor-jkskj-5467df7468-v4mwt                            1/1     Running   0          11d
minio-ci-technolution-eventsource-2kklg-64696b978d-8vxjx          1/1     Running   0          2d21h
minio-ci-technolution-sensor-tb7r4-7f5d686f89-r8jwq               1/1     Running   0          11d
minio-event-source-eventsource-xsmx4-7dd6cb4577-d55pm             1/1     Running   15         27d
minio-helm-event-source-eventsource-5hpl4-7b78966d7f-htln7        1/1     Running   19         27d
minio-helm-sensor-sensor-fh9bx-779b48ff7c-h7zmw                   1/1     Running   18         27d
minio-helm-technolution-event-source-eventsource-csgbm-65fd4bp4   1/1     Running   0          13d
minio-helm-technolution-sensor-sensor-q4f42-6d4cbf5947-jbz7q      1/1     Running   0          13d
minio-sensor-sensor-k66vk-66b9d7c7b4-bt94d                        1/1     Running   15         27d
sensor-controller-b97ffb4c4-2m5cl                                 1/1     Running   0          27d
webhook-eventsource-qrfnw-55bff8bf99-g2jb8                        1/1     Running   13         27d
webhook-sensor-tx7px-7b8f8689f4-6hkww                             1/1     Running   12         27d
```

A (previous) log from a restarted eventSource Pod:

```
{"level":"error","ts":1610374503.183892,"logger":"argo-events.eventsource","caller":"driver/nats.go:102","msg":"Failed to connect to NATS server","eventSourceName":"minio-ci","clientID":"minio-ci-eventsource-cgpv9-54f67d7bb5-nh5j4","error":"nats: no servers available for connection","stacktrace":"github.com/argoproj/argo-events/eventbus/driver.(*natsStreaming).Connect\n\t/home/runner/work/argo-events/argo-events/eventbus/driver/nats.go:102\ngithub.com/argoproj/argo-events/eventsources.(*EventSourceAdaptor).Start.func1\n\t/home/runner/work/argo-events/argo-events/eventsources/eventing.go:271\ngithub.com/argoproj/argo-events/common.Connect.func1\n\t/home/runner/work/argo-events/argo-events/common/retry.go:75\nk8s.io/apimachinery/pkg/util/wait.ExponentialBackoff\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.17.6-beta.0/pkg/util/wait/wait.go:292\ngithub.com/argoproj/argo-events/common.Connect\n\t/home/runner/work/argo-events/argo-events/common/retry.go:74\ngithub.com/argoproj/argo-events/eventsources.(*EventSourceAdaptor).Start\n\t/home/runner/work/argo-events/argo-events/eventsources/eventing.go:270\nmain.main\n\t/home/runner/work/argo-events/argo-events/eventsources/cmd/main.go:60\nruntime.main\n\t/opt/hostedtoolcache/go/1.14.11/x64/src/runtime/proc.go:203"}
{"level":"error","ts":1610374503.183964,"logger":"argo-events.eventsource","caller":"eventsources/eventing.go:274","msg":"failed to connect to eventbus","eventSourceName":"minio-ci","error":"timed out waiting for the condition","stacktrace":"github.com/argoproj/argo-events/eventsources.(*EventSourceAdaptor).Start\n\t/home/runner/work/argo-events/argo-events/eventsources/eventing.go:274\nmain.main\n\t/home/runner/work/argo-events/argo-events/eventsources/cmd/main.go:60\nruntime.main\n\t/opt/hostedtoolcache/go/1.14.11/x64/src/runtime/proc.go:203"}
{"level":"fatal","ts":1610374503.1839862,"logger":"argo-events.eventsource","caller":"cmd/main.go:61","msg":"failed to start eventsource server","eventSourceName":"minio-ci","error":"timed out waiting for the condition","stacktrace":"main.main\n\t/home/runner/work/argo-events/argo-events/eventsources/cmd/main.go:61\nruntime.main\n\t/opt/hostedtoolcache/go/1.14.11/x64/src/runtime/proc.go:203"}
```

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

### PR DESCRIPTION
**Pull request by whynowy**
Signed-off-by: Derek Wang <whynowy@gmail.com>

Checklist:

* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo-events/blob/master/USERS.md).

### CODE REVIEW

File: Dockerfile [hunk 1]
```diff
@@ -47,7 +47,7 @@ ENTRYPOINT [ "/bin/eventsource" ]
 ####################################################################################################
 # sensor
 ####################################################################################################
-FROM alpine as sensor
+FROM alpine:3.12.3 as sensor
```
Comment (whynowy) [inline Dockerfile:50]: The latest `alpine` release (v3.13.x) has DNS resolving issue, pin to `3.12.3`.

File: eventsources/eventing.go [hunk 2]
```diff
@@ -382,3 +391,10 @@ func (e *EventSourceAdaptor) Start(ctx context.Context) error {
 		}
 	}
 }
+
+func generateClientID(hostname string) string {
+	s1 := rand.NewSource(time.Now().UnixNano())
```
Comment (alexec) [inline eventsources/eventing.go:396]: rather than using rand, what about using an RFC compliant UUID?

Comment (alexec) [reply eventsources/eventing.go:396]: https://github.com/google/uuid

**Review by alexec — APPROVED** [review]
