### PR TITLE
fix(amqp): Return error when channel is closed. Fixes #920

### LINKED ISSUE #920: Infinite creation of new Workflows.
## Summary 

When we start Argo Workflows it works ok, but in some moment (let's say two or three hours later) it starts creating new workflows and it never stops. This is huge issue for us, because this is basically an infinite loop - new workflows are constantly creating. It affects our resources a lot.

Note: We are triggering workflows via AMQP sensor.

## Diagnostics

What Kubernetes provider are you using?
- EKS

What version of Argo Workflows are you running?
2.7.6

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: amqp
  namespace: argo-events
spec:
  template:
    serviceAccountName: events
  dependencies:
    - name: test-dep
      eventSourceName: amqp
      eventName: example
  triggers:
    - template:
        name: amqp-workflow-trigger
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                namespace: argo-workflows
                generateName: sync-by-id-
              spec:
                entrypoint: sync
                arguments:
                  parameters:
                    - name: id
                      value: "123"
                    - name: image
                      value: "aaa"
                serviceAccountName: workflow
                templates:
                  - name: step
                  inputs: 
                    parameters: 
                      - name: id
                        value: "123"
                      - name: image
                        value: "aaa"
                  container:
                    image: "{{`{{inputs.parameters.image}}`}}"
                    args: ["{{`{{inputs.parameters.id}}`}}"]
                  - name: sync
                    dag:
                      tasks:
                        - name: first-step
                          template: step
                          arguments:
                            parameters: [
                              {name: id, value: "{{`{{workflow.parameters.id}}`}}"},
                              {name: image, value: "first-step-image:tag"}
                            ]
                        - name: second-step
                          dependencies: [first-step]
                          template: step
                          arguments:
                            parameters: [
                              {name: id, value: "{{`{{workflow.parameters.id}}`}}"},
                              {name: image, value: "second-step-image:tag"}
                            ]
          parameters:
            - src:
                dependencyName: test-dep
                dataKey: body.id
              dest: spec.arguments.parameters.0.value
```

Status regarding the workflows: It works ok for some time, and then it starts creating new workflows that are in pending state.

Here is the link to the video we've recorded, so you can see what's showing on the UI: https://gofile.io/d/cauAUQ

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by whynowy**
When connection/channel is closed, it keeps reading empty messages from the channel without checking if it's successful.

Checklist:

* [x] Either (a) I've created an [feature request](https://github.com/argoproj/argo-events/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] I've signed the CLA.
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My builds are green. Try syncing with master if they are not. 
* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo-events/blob/master/USERS.md).

Fixes #920

### CODE REVIEW

File: eventsources/sources/amqp/start.go [hunk 1]
```diff
@@ -106,7 +106,11 @@ func (el *EventListener) StartListening(ctx context.Context, dispatch func([]byt
 	log.Info("listening to messages on channel...")
 	for {
 		select {
-		case msg := <-delivery:
+		case msg, ok := <-delivery:
+			if !ok {
+				log.Error("failed to read a message, channel might have been closed")
+				return errors.New("channel might have been closed")
```
Comment (whynowy) [inline eventsources/sources/amqp/start.go:112]: Will have retries in eventing.go.

Comment (AleksandarGradina) [reply eventsources/sources/amqp/start.go:112]: @whynowy thanks for your effort! 
Can you give me the PR for retries, so i can follow it?

Comment (whynowy) [reply eventsources/sources/amqp/start.go:112]: https://github.com/argoproj/argo-events/pull/927

**Review by VaibhavPage — APPROVED** [review]
