### PR TITLE
fix: Kafka consumer fails to reconnect and sensor stops working

### LINKED ISSUE #3481: Kafka consumer fails to reconnect and sensor stops working
**Describe the bug**
Argo sensor fails to reconnect to Kafka and enters a state where it no longer retries the connection after encountering an error. The following error message is observed in the logs:

`{"level":"error","ts":1726637015.3759136,"logger":"argo-events.sensor","caller":"sensor/kafka_sensor.go:222","msg":"Failed to consume","sensorName":"some-webhook","error":"kafka: response did not contain all the expected topic/partition blocks","stacktrace":"github.com/argoproj/argo-events/eventbus/kafka/sensor.(*KafkaSensor).Listen\n\t/home/runner/work/argo-events/argo-events/eventbus/kafka/sensor/kafka_sensor.go:222"}`

This issue arises when the Kafka consumer receives incomplete response. Sarama indicates that the response was syntactically valid but lacked the expected topic/partition blocks. The sensor fails to recover from this state and does not attempt to reconnect to Kafka. Currently, the only workaround is to manually terminate the pod, which triggers the creation of a new pod that successfully connects to Kafka. (For Ref: https://github.com/IBM/sarama/blob/9ae475a39e964d257e630d75d02541ab5fa70b1c/errors.go#L23C5-L23C26)

Similar to #2711 #3273 (both are in "Closed as not planned")

**To Reproduce**
This scenario is difficult to reproduce. In our experience, we have seen it happen when the sensor pods are moved on to a different/new node or (rarely) when a deployment is restarted. 

**Expected behavior**
Expected behavior is for the sensor to be able to retry connection or fail fast. 

**Environment (please complete the following information):**
 - Kubernetes: 1.30.7
 - Argo: v2.13.2
 - Argo Events: v1.9.2

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

### PR DESCRIPTION
**Pull request by smunukutla-mycarrier**
PR to fix #3481

### CODE REVIEW

**Comment by smunukutla-mycarrier** [comment]
Created a new branch with latest code to workaround merge hell and signoff issue. I apologize for the trouble.

File: pkg/eventbus/kafka/sensor/kafka_sensor.go [hunk 1]
```diff
@@ -219,6 +219,11 @@ func (s *KafkaSensor) Listen(ctx context.Context) {
 				)
 			}
 
+			// Fail fast if the server returns an incomplete response
```
Comment (whynowy) [inline pkg/eventbus/kafka/sensor/kafka_sensor.go:222]: Extra space in the end, that's why the CI fails.

Comment (smunukutla-mycarrier) [reply pkg/eventbus/kafka/sensor/kafka_sensor.go]: Fixed. Thanks!

**Review by whynowy — APPROVED** [review]
